version: "3"

networks:
  localnet:
    driver: bridge

services:
  java_app_insight:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app_insight
    networks:
      - localnet
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m -Dserver.port=8080
      - JAVA_TOOL_OPTIONS=-javaagent:/files/applicationinsights-agent-3.2.11.jar

      - APPLICATIONINSIGHTS_CONNECTION_STRING=REDACTED
      - APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL=ALL
      - APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL=TRACE
      - APPLICATIONINSIGHTS_ROLE_NAME=tmp-api-client
      - APPLICATIONINSIGHTS_STATSBEAT_DISABLED=true
      - APPINSIGHTS_PROFILERFEATURE_VERSION=1.0.0
    ports:
      - 8080:8080
    restart: unless-stopped